using ServISData.Attributes;
using ServISData.Interfaces;

namespace ServISData.Models
{
	public class AutogeneratedMessage : IItem
	{
		public int Id { get; set; }
		public string Subject { get; set; } = null!;
		public string Message { get; set; } = null!;
		public For ForWhom { get; set; }

		public enum For
		{
			// tags are from (are the same as in) AutogeneratedMessageForm.Tags
			[AutogeneratedMessageData(
				label: "Pre víťaza aukcie",
				defaultSubject: "Vyhrali ste #nazov_stroja v aukcii!",
				defaultMessage: "Gratulujeme, vyhrali ste #nazov_stroja v aukcii za #max_ponuka €.\n" +
				"O ďalšom postupe Vás budeme informovať.\n" +
				"(Tento email bol vygenerovaný automaticky. Prosíme, aby ste naň neodpovedali.)",
				tags: new[] { "#nazov_stroja", "#pociatocna_cena", "#ponuknuta_cena",
					"#meno_vyhercu", "#mobil_vyhercu", "#email_vyhercu", "#bydlisko_vyhercu" }
			)]
			AuctionWinner,
			[AutogeneratedMessageData(
				label: "Pre porazeného v aukcii",
				defaultSubject: "Aukcia s predmetom #nazov_stroja sa skončila",
				defaultMessage: "S ľútosťou Vám oznamujeme, že ste aukciu s predmetom #nazov_stroja nevyhrali.\n" +
				"Predmet bol vydražený na cenu #max_ponuka €.\n" +
				"Vy ste ponúkli #ponuknuta_cena.\n" +
				"Prajeme viacej šťastia nabudúce ;)\n" +
				"(Tento email bol vygenerovaný automaticky. Prosíme, aby ste naň neodpovedali.)",
				tags: new[] { "#nazov_stroja", "#pociatocna_cena", "#max_ponuka", "#ponuknuta_cena",
					"#meno_ucastnika", "#mobil_ucastnika", "#email_ucastnika", "#bydlisko_ucastnika" }
			)]
			AuctionLoser,
			[AutogeneratedMessageData(
				label: "Pre admina, keď aukcia skončí",
				defaultSubject: "Odpoveď na výhru #nazov_stroja v aukcii",
				defaultMessage: "Výherný predmet: #nazov_stroja\n" +
				"Ponúknutá cena: #max_ponuka €.\n" +
				"Meno výhercu: #meno_vyhercu\n" +
				"Kontakt na výhercu:\n" +
				"\t-telefón: #mobil_vyhercu\n" +
				"\t-email: #email_vyhercu",
				tags: new[] { "#nazov_stroja", "#pociatocna_cena", "#max_ponuka", "#meno_vyhercu",
					"#mobil_vyhercu", "#email_vyhercu", "#bydlisko_vyhercu" }
			)]
			AdminWhenAuctionEndsWithWinner,
			[AutogeneratedMessageData(
				label: "Pre admina, keď aukcia skončí (bez účastníkov)",
				defaultSubject: "Aukcia s #nazov_stroja skončila bez výhercu",
				defaultMessage: "Aukčný predmet: #nazov_stroja\n" +
				"Počiatočná cena: #pociatocna_cena €.",
				tags: new[] { "#nazov_stroja", "#pociatocna_cena" }
			)]
			AdminWhenAuctionEndsWithoutWinner
		}
	}
}
