using MimeKit;
using ServISData.Interfaces;
using ServISData.Models;
using ServISWebApp.Shared;
using ServISWebApp.Shared.Extensions;

namespace ServISWebApp.BackgroundServices
{
	public class AuctionEvaluatorService : TimerService
	{
		private readonly IServISApi api;
		private readonly EmailManager emailManager;
		private readonly string baseUrl;
		private event Func<Task>? updateEvent;

		public AuctionEvaluatorService(
			IServISApi api,
			EmailManager emailManager,
			string baseUrl
		) : base(TimeSpan.FromMinutes(1))
		{
			this.api = api;
			this.emailManager = emailManager;
			this.baseUrl = baseUrl;

			RegisterEventHandler();
		}

		protected override Func<Task>? GetEventHandlers() => updateEvent;

		private async Task NotifyAdminAuctionEndedWithoutWinner(DateTime dateTimeNow, AuctionOffer aoe)
		{
			var excavator = aoe.Excavator;
			var linkToAuctionOfferDetail = $"{baseUrl}/aukcna-ponuka/{aoe.Id}";

			var header = new Header(
				field: "X-ServIS-url",
				value: linkToAuctionOfferDetail
			);

			var autogeneratedMessage = 
				await api.GetAutogeneratedMessageAsync(AutogeneratedMessage.For.AdminWhenAuctionEndsWithoutWinner);

			var auctionSummary = new AuctionSummary(aoe);

			var subject = autogeneratedMessage.FormatSubject(auctionSummary);
			var message = autogeneratedMessage.FormatMessage(auctionSummary);

			var emailForAdmin = new Email
			{
				DateTime = dateTimeNow,
				FromName = emailManager.EmailName,
				FromAddress = emailManager.EmailAddress,
				ToName = emailManager.EmailName,
				ToAddress = emailManager.EmailAddress,
				Headers = new() { header },
				Subject = subject,
				Text = message
			};

			_ = emailManager.SendEmailAsync(emailForAdmin);
		}

		private async Task NotifyAdminAuctionEndedWithWinner(
			DateTime dateTimeNow,
			AuctionBid maxAuctionBid,
			User auctionWinner,
			string auctionWinnerFullname
		)
		{
			var linkToAuctionOfferDetail = $"{baseUrl}/aukcna-ponuka/{maxAuctionBid.AuctionOffer.Id}";

			var header = new Header(
				field: "X-ServIS-url",
				value: linkToAuctionOfferDetail
			);

			var autogeneratedMessage =
				await api.GetAutogeneratedMessageAsync(AutogeneratedMessage.For.AdminWhenAuctionEndsWithWinner);

			var auctionSummary = new AuctionSummary(maxAuctionBid.AuctionOffer, maxAuctionBid);

			var subject = autogeneratedMessage.FormatSubject(auctionSummary);
			var message = autogeneratedMessage.FormatMessage(auctionSummary);

			var emailForAdmin = new Email
			{
				DateTime = dateTimeNow,
				FromName = auctionWinnerFullname,
				FromAddress = auctionWinner.Email,
				ToName = emailManager.EmailName,
				ToAddress = emailManager.EmailAddress,
				Headers = new() { header },
				Subject = subject,
				Text = message
			};

			_ = emailManager.SendEmailAsync(emailForAdmin);
		}

		private void NotifyUser(DateTime dateTimeNow, User user, string userFullname, string subject, string text)
		{
			var header = new Header(
				field: "X-ServIS-autogenerated",
				value: "true"
			);

			var emailForWinner = new Email
			{
				DateTime = dateTimeNow,
				Headers = new() { header },
				FromName = emailManager.EmailName,
				FromAddress = emailManager.EmailAddress,
				ToName = userFullname,
				ToAddress = user.Email,
				Subject = subject,
				Text = text
			};

			_ = emailManager.SendEmailAsync(emailForWinner);
		}

		private async Task NotifyWinner(
			DateTime dateTimeNow,
			AuctionBid maxAuctionBid,
			User auctionWinner,
			string auctionWinnerFullname
		)
		{
			var autogeneratedMessage =
				await api.GetAutogeneratedMessageAsync(AutogeneratedMessage.For.AuctionWinner);

			var auctionSummary = new AuctionSummary(maxAuctionBid.AuctionOffer, maxAuctionBid);

			var subject = autogeneratedMessage.FormatSubject(auctionSummary);
			var message = autogeneratedMessage.FormatMessage(auctionSummary);

			NotifyUser(dateTimeNow, auctionWinner, auctionWinnerFullname, subject, message);
		}

		private void NotifyLoser(
			DateTime dateTimeNow,
			User auctionLoser,
			string auctionLoserFullname,
			string subject,
			string message
		)
		{
			NotifyUser(dateTimeNow, auctionLoser, auctionLoserFullname, subject, message);
		}

		private async Task<(List<string> FormattedSubjects, List<string> FormattedMessages)> GetFormattedSubjectsAndMessages(
			List<AuctionBid> auctionBids,
			AuctionBid winnerAuctionBid
		)
		{
			var autogeneratedMessage =
				await api.GetAutogeneratedMessageAsync(AutogeneratedMessage.For.AuctionLoser);

			var auctionSummaries = new List<AuctionSummary>(auctionBids.Count);
			for (int i = 0; i < auctionBids.Count; i++)
			{
				var auctionSummary = new AuctionSummary(winnerAuctionBid.AuctionOffer, auctionBids[i], winnerAuctionBid);
				auctionSummaries.Add(auctionSummary);
			}

			var formattedSubjects = autogeneratedMessage.FormatSubject(auctionSummaries);
			var formattedMessages = autogeneratedMessage.FormatMessage(auctionSummaries);

			return (formattedSubjects, formattedMessages);
		}

		private async Task NotifyLosers(
			DateTime dateTimeNow,
			List<AuctionBid> lostAuctionBids,
			AuctionBid maxAuctionBid
		)
		{
			var (formattedSubjects, formattedMessages) = await GetFormattedSubjectsAndMessages(lostAuctionBids, maxAuctionBid);

			for (int i = 0; i < lostAuctionBids.Count; i++)
			{
				var auctionLoser = lostAuctionBids[i].User;
				var loserFullname = $"{auctionLoser.Name} {auctionLoser.Surname}";

				NotifyLoser(dateTimeNow, auctionLoser, loserFullname, formattedSubjects[i], formattedMessages[i]);
			}
		}

		private async Task EvaluateAuctionOffersAsync(
			DateTime dateTimeNow,
			List<AuctionOffer> endedAuctionOffers
		)
		{
			foreach (var offer in endedAuctionOffers)
			{
				var maxAuctionBid = await api.GetMaxAuctionBidAsync(offer.Id);
				if (maxAuctionBid is null)
				{// there were no bids (no participants)
					_ = NotifyAdminAuctionEndedWithoutWinner(dateTimeNow, offer);
					offer.OfferEnd += TimeSpan.FromDays(7);
				}
				else
				{
					var auctionWinner = maxAuctionBid.User;
					var auctionWinnerFullname = $"{auctionWinner.Name} {auctionWinner.Surname}";

					_ = NotifyWinner(dateTimeNow, maxAuctionBid, auctionWinner, auctionWinnerFullname);

					_ = NotifyAdminAuctionEndedWithWinner(dateTimeNow, maxAuctionBid, auctionWinner, auctionWinnerFullname);

					var lostAuctionBids = await api.GetLostAuctionBidsAsync(offer.Id);
					_ = NotifyLosers(dateTimeNow, lostAuctionBids, maxAuctionBid);
				
					offer.IsEvaluated = true;
				}

				_ = api.SaveAuctionOfferAsync(offer);
			}
		}

		private async Task<List<AuctionOffer>> GetEndedAuctionOffers(DateTime dateTimeNow, bool includeEvaluated = true)
		{
			var auctionOffers = await api.GetAuctionOffersAsync();

			var auctionOffersEnded = auctionOffers
				.Where(ao => (ao.OfferEnd < dateTimeNow) && (includeEvaluated || !ao.IsEvaluated))
				.ToList();

			return auctionOffersEnded;
		}

		private void RegisterEventHandler()
		{
			updateEvent += async () =>
			{
				var dateTimeNow = DateTime.Now;
				var endedAuctionOffers = await GetEndedAuctionOffers(dateTimeNow, includeEvaluated: false);
				if (endedAuctionOffers.Count == 0)
				{
					return;
				}

				await EvaluateAuctionOffersAsync(dateTimeNow, endedAuctionOffers);
			};
		}
	}
}
