using ServISData.Attributes;
using ServISData.Models;

namespace ServISData
{
    /// <summary>
    /// Provides extension methods for the <see cref="AutogeneratedMessage.For"/> enum.
    /// </summary>
    public static class AutogeneratedMessageForExtensions
	{
        /// <summary>
        /// Retrieves the label associated with the specified <see cref="AutogeneratedMessage.For"/> value.
        /// </summary>
        /// <param name="forWhom">The <see cref="AutogeneratedMessage.For"/> value.</param>
        /// <returns>The label of the <see cref="AutogeneratedMessage.For"/> value.</returns>
        public static string GetLabel(this AutogeneratedMessage.For forWhom)
		{
			var customAttribute = GetCustomAttribute(forWhom);

			return customAttribute.Label;
		}

        /// <summary>
        /// Retrieves the default subject associated with the specified <see cref="AutogeneratedMessage.For"/> value.
        /// </summary>
        /// <param name="forWhom">The <see cref="AutogeneratedMessage.For"/> value.</param>
        /// <returns>The default subject of the <see cref="AutogeneratedMessage.For"/> value.</returns>
        public static string GetDefaultSubject(this AutogeneratedMessage.For forWhom)
		{
			var customAttribute = GetCustomAttribute(forWhom);

			return customAttribute.DefaultSubject;
		}

        /// <summary>
        /// Retrieves the default message associated with the specified <see cref="AutogeneratedMessage.For"/> value.
        /// </summary>
        /// <param name="forWhom">The <see cref="AutogeneratedMessage.For"/> value.</param>
        /// <returns>The default message of the <see cref="AutogeneratedMessage.For"/> value.</returns>
        public static string GetDefaultMessage(this AutogeneratedMessage.For forWhom)
		{
			var customAttribute = GetCustomAttribute(forWhom);

			return customAttribute.DefaultMessage;
		}

        /// <summary>
        /// Retrieves the tags associated with the specified <see cref="AutogeneratedMessage.For"/> value.
        /// </summary>
        /// <param name="forWhom">The <see cref="AutogeneratedMessage.For"/> value.</param>
        /// <returns>The tags of the <see cref="AutogeneratedMessage.For"/> value.</returns>
        public static string[] GetTags(this AutogeneratedMessage.For forWhom)
		{
			var customAttribute = GetCustomAttribute(forWhom);

			return customAttribute.Tags;
		}

		private static AutogeneratedMessageDataAttribute GetCustomAttribute(AutogeneratedMessage.For forWhom)
		{
			var inputTypeEnumName = Enum.GetName(forWhom);
			if (inputTypeEnumName is null)
			{
				throw new Exception($"Enum '{nameof(AutogeneratedMessage.For)}' does NOT contain constant '{forWhom}'");
			}

			var customAttribute = forWhom.GetType()
				.GetField(inputTypeEnumName)
				?.GetCustomAttributes(false)
				.OfType<AutogeneratedMessageDataAttribute>()
				.Single();
			if (customAttribute is null)
			{
				throw new Exception(
					$"Enum '{nameof(AutogeneratedMessage.For)}' does NOT have (single) attribute '{nameof(AutogeneratedMessageDataAttribute)}'");
			}

			return customAttribute;
		}
	}
}
