using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ServISData.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "additional_equipment_brands",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    brand = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_additional_equipment_brands", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "additional_equipment_categories",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    category = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_additional_equipment_categories", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "autogenerated_messages",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    subject = table.Column<string>(type: "text", nullable: false),
                    message = table.Column<string>(type: "text", nullable: false),
                    for_whom = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_autogenerated_messages", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "excavator_brands",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    brand = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_excavator_brands", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "excavator_categories",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    category = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_excavator_categories", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "excavator_property_types",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    name = table.Column<string>(type: "text", nullable: false),
                    input_type = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_excavator_property_types", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "spare_parts",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    catalog_number = table.Column<int>(type: "integer", nullable: false),
                    name = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_spare_parts", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "users",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    username = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    password = table.Column<string>(type: "text", nullable: false),
                    role = table.Column<string>(type: "text", nullable: false),
                    name = table.Column<string>(type: "character varying(35)", maxLength: 35, nullable: false),
                    surname = table.Column<string>(type: "character varying(35)", maxLength: 35, nullable: false),
                    phone_number = table.Column<string>(type: "text", nullable: true),
                    email = table.Column<string>(type: "text", nullable: false),
                    residence = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    is_temporary = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_users", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "additional_equipments",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    excavator_category_id = table.Column<int>(type: "integer", nullable: false),
                    category_id = table.Column<int>(type: "integer", nullable: false),
                    brand_id = table.Column<int>(type: "integer", nullable: false),
                    name = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false),
                    description = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_additional_equipments", x => x.id);
                    table.ForeignKey(
                        name: "fk_additional_equipments_additional_equipment_brands_brand_id",
                        column: x => x.brand_id,
                        principalTable: "additional_equipment_brands",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_additional_equipments_additional_equipment_categories_categ",
                        column: x => x.category_id,
                        principalTable: "additional_equipment_categories",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_additional_equipments_excavator_categories_excavator_catego",
                        column: x => x.excavator_category_id,
                        principalTable: "excavator_categories",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "excavator_types",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    brand_id = table.Column<int>(type: "integer", nullable: false),
                    category_id = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_excavator_types", x => x.id);
                    table.ForeignKey(
                        name: "fk_excavator_types_excavator_brands_brand_id",
                        column: x => x.brand_id,
                        principalTable: "excavator_brands",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_excavator_types_excavator_categories_category_id",
                        column: x => x.category_id,
                        principalTable: "excavator_categories",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "additional_equipment_photos",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    additional_equipment_id = table.Column<int>(type: "integer", nullable: false),
                    photo = table.Column<byte[]>(type: "bytea", nullable: false),
                    is_title = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_additional_equipment_photos", x => x.id);
                    table.ForeignKey(
                        name: "fk_additional_equipment_photos_additional_equipments_additiona",
                        column: x => x.additional_equipment_id,
                        principalTable: "additional_equipments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "excavator_property_type_excavator_type",
                columns: table => new
                {
                    excavator_types_with_this_property_id = table.Column<int>(type: "integer", nullable: false),
                    property_types_id = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_excavator_property_type_excavator_type", x => new { x.excavator_types_with_this_property_id, x.property_types_id });
                    table.ForeignKey(
                        name: "fk_excavator_property_type_excavator_type_excavator_property_t",
                        column: x => x.property_types_id,
                        principalTable: "excavator_property_types",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_excavator_property_type_excavator_type_excavator_types_exca",
                        column: x => x.excavator_types_with_this_property_id,
                        principalTable: "excavator_types",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "excavators",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    name = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false),
                    description = table.Column<string>(type: "text", nullable: false),
                    is_for_auction_only = table.Column<bool>(type: "boolean", nullable: false),
                    type_id = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_excavators", x => x.id);
                    table.ForeignKey(
                        name: "fk_excavators_excavator_types_type_id",
                        column: x => x.type_id,
                        principalTable: "excavator_types",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "main_offers",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    excavator_type_id = table.Column<int>(type: "integer", nullable: false),
                    photo = table.Column<byte[]>(type: "bytea", nullable: false),
                    description = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_main_offers", x => x.id);
                    table.ForeignKey(
                        name: "fk_main_offers_excavator_types_excavator_type_id",
                        column: x => x.excavator_type_id,
                        principalTable: "excavator_types",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "auction_offers",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    excavator_id = table.Column<int>(type: "integer", nullable: false),
                    description = table.Column<string>(type: "text", nullable: false),
                    offer_end = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    starting_bid = table.Column<decimal>(type: "numeric(11,2)", nullable: false),
                    is_evaluated = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_auction_offers", x => x.id);
                    table.ForeignKey(
                        name: "fk_auction_offers_excavators_excavator_id",
                        column: x => x.excavator_id,
                        principalTable: "excavators",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "excavator_photos",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    excavator_id = table.Column<int>(type: "integer", nullable: false),
                    photo = table.Column<byte[]>(type: "bytea", nullable: false),
                    is_title = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_excavator_photos", x => x.id);
                    table.ForeignKey(
                        name: "fk_excavator_photos_excavators_excavator_id",
                        column: x => x.excavator_id,
                        principalTable: "excavators",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "excavator_properties",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    value = table.Column<string>(type: "text", nullable: false),
                    property_type_id = table.Column<int>(type: "integer", nullable: false),
                    excavator_id = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_excavator_properties", x => x.id);
                    table.ForeignKey(
                        name: "fk_excavator_properties_excavator_property_types_property_type",
                        column: x => x.property_type_id,
                        principalTable: "excavator_property_types",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_excavator_properties_excavators_excavator_id",
                        column: x => x.excavator_id,
                        principalTable: "excavators",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "excavator_spare_part",
                columns: table => new
                {
                    excavators_id = table.Column<int>(type: "integer", nullable: false),
                    spare_parts_id = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_excavator_spare_part", x => new { x.excavators_id, x.spare_parts_id });
                    table.ForeignKey(
                        name: "fk_excavator_spare_part_excavators_excavators_id",
                        column: x => x.excavators_id,
                        principalTable: "excavators",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_excavator_spare_part_spare_parts_spare_parts_id",
                        column: x => x.spare_parts_id,
                        principalTable: "spare_parts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "auction_bids",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    user_id = table.Column<int>(type: "integer", nullable: false),
                    auction_offer_id = table.Column<int>(type: "integer", nullable: false),
                    bid = table.Column<decimal>(type: "numeric(11,2)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_auction_bids", x => x.id);
                    table.ForeignKey(
                        name: "fk_auction_bids_auction_offers_auction_offer_id",
                        column: x => x.auction_offer_id,
                        principalTable: "auction_offers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_auction_bids_users_user_id",
                        column: x => x.user_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_additional_equipment_photos_additional_equipment_id",
                table: "additional_equipment_photos",
                column: "additional_equipment_id");

            migrationBuilder.CreateIndex(
                name: "ix_additional_equipments_brand_id",
                table: "additional_equipments",
                column: "brand_id");

            migrationBuilder.CreateIndex(
                name: "ix_additional_equipments_category_id",
                table: "additional_equipments",
                column: "category_id");

            migrationBuilder.CreateIndex(
                name: "ix_additional_equipments_excavator_category_id",
                table: "additional_equipments",
                column: "excavator_category_id");

            migrationBuilder.CreateIndex(
                name: "ix_auction_bids_auction_offer_id",
                table: "auction_bids",
                column: "auction_offer_id");

            migrationBuilder.CreateIndex(
                name: "ix_auction_bids_user_id",
                table: "auction_bids",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ix_auction_offers_excavator_id",
                table: "auction_offers",
                column: "excavator_id");

            migrationBuilder.CreateIndex(
                name: "ix_excavator_photos_excavator_id",
                table: "excavator_photos",
                column: "excavator_id");

            migrationBuilder.CreateIndex(
                name: "ix_excavator_properties_excavator_id",
                table: "excavator_properties",
                column: "excavator_id");

            migrationBuilder.CreateIndex(
                name: "ix_excavator_properties_property_type_id",
                table: "excavator_properties",
                column: "property_type_id");

            migrationBuilder.CreateIndex(
                name: "ix_excavator_property_type_excavator_type_property_types_id",
                table: "excavator_property_type_excavator_type",
                column: "property_types_id");

            migrationBuilder.CreateIndex(
                name: "ix_excavator_spare_part_spare_parts_id",
                table: "excavator_spare_part",
                column: "spare_parts_id");

            migrationBuilder.CreateIndex(
                name: "ix_excavator_types_brand_id",
                table: "excavator_types",
                column: "brand_id");

            migrationBuilder.CreateIndex(
                name: "ix_excavator_types_category_id",
                table: "excavator_types",
                column: "category_id");

            migrationBuilder.CreateIndex(
                name: "ix_excavators_type_id",
                table: "excavators",
                column: "type_id");

            migrationBuilder.CreateIndex(
                name: "ix_main_offers_excavator_type_id",
                table: "main_offers",
                column: "excavator_type_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "additional_equipment_photos");

            migrationBuilder.DropTable(
                name: "auction_bids");

            migrationBuilder.DropTable(
                name: "autogenerated_messages");

            migrationBuilder.DropTable(
                name: "excavator_photos");

            migrationBuilder.DropTable(
                name: "excavator_properties");

            migrationBuilder.DropTable(
                name: "excavator_property_type_excavator_type");

            migrationBuilder.DropTable(
                name: "excavator_spare_part");

            migrationBuilder.DropTable(
                name: "main_offers");

            migrationBuilder.DropTable(
                name: "additional_equipments");

            migrationBuilder.DropTable(
                name: "auction_offers");

            migrationBuilder.DropTable(
                name: "users");

            migrationBuilder.DropTable(
                name: "excavator_property_types");

            migrationBuilder.DropTable(
                name: "spare_parts");

            migrationBuilder.DropTable(
                name: "additional_equipment_brands");

            migrationBuilder.DropTable(
                name: "additional_equipment_categories");

            migrationBuilder.DropTable(
                name: "excavators");

            migrationBuilder.DropTable(
                name: "excavator_types");

            migrationBuilder.DropTable(
                name: "excavator_brands");

            migrationBuilder.DropTable(
                name: "excavator_categories");
        }
    }
}
