// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServISData;

#nullable disable

namespace ServISData.Migrations
{
    [DbContext(typeof(ServISDbContext))]
    [Migration("20260614135244_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExcavatorPropertyTypeExcavatorType", b =>
                {
                    b.Property<int>("ExcavatorTypesWithThisPropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("excavator_types_with_this_property_id");

                    b.Property<int>("PropertyTypesId")
                        .HasColumnType("integer")
                        .HasColumnName("property_types_id");

                    b.HasKey("ExcavatorTypesWithThisPropertyId", "PropertyTypesId")
                        .HasName("pk_excavator_property_type_excavator_type");

                    b.HasIndex("PropertyTypesId")
                        .HasDatabaseName("ix_excavator_property_type_excavator_type_property_types_id");

                    b.ToTable("excavator_property_type_excavator_type", (string)null);
                });

            modelBuilder.Entity("ExcavatorSparePart", b =>
                {
                    b.Property<int>("ExcavatorsId")
                        .HasColumnType("integer")
                        .HasColumnName("excavators_id");

                    b.Property<int>("SparePartsId")
                        .HasColumnType("integer")
                        .HasColumnName("spare_parts_id");

                    b.HasKey("ExcavatorsId", "SparePartsId")
                        .HasName("pk_excavator_spare_part");

                    b.HasIndex("SparePartsId")
                        .HasDatabaseName("ix_excavator_spare_part_spare_parts_id");

                    b.ToTable("excavator_spare_part", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.AdditionalEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExcavatorCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("excavator_category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_additional_equipments");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_additional_equipments_brand_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_additional_equipments_category_id");

                    b.HasIndex("ExcavatorCategoryId")
                        .HasDatabaseName("ix_additional_equipments_excavator_category_id");

                    b.ToTable("additional_equipments", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.AdditionalEquipmentBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("brand");

                    b.HasKey("Id")
                        .HasName("pk_additional_equipment_brands");

                    b.ToTable("additional_equipment_brands", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.AdditionalEquipmentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.HasKey("Id")
                        .HasName("pk_additional_equipment_categories");

                    b.ToTable("additional_equipment_categories", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.AdditionalEquipmentPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdditionalEquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("additional_equipment_id");

                    b.Property<bool>("IsTitle")
                        .HasColumnType("boolean")
                        .HasColumnName("is_title");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("photo");

                    b.HasKey("Id")
                        .HasName("pk_additional_equipment_photos");

                    b.HasIndex("AdditionalEquipmentId")
                        .HasDatabaseName("ix_additional_equipment_photos_additional_equipment_id");

                    b.ToTable("additional_equipment_photos", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.AuctionBid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionOfferId")
                        .HasColumnType("integer")
                        .HasColumnName("auction_offer_id");

                    b.Property<decimal>("Bid")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("bid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auction_bids");

                    b.HasIndex("AuctionOfferId")
                        .HasDatabaseName("ix_auction_bids_auction_offer_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auction_bids_user_id");

                    b.ToTable("auction_bids", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.AuctionOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExcavatorId")
                        .HasColumnType("integer")
                        .HasColumnName("excavator_id");

                    b.Property<bool>("IsEvaluated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_evaluated");

                    b.Property<DateTime>("OfferEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offer_end");

                    b.Property<decimal>("StartingBid")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("starting_bid");

                    b.HasKey("Id")
                        .HasName("pk_auction_offers");

                    b.HasIndex("ExcavatorId")
                        .HasDatabaseName("ix_auction_offers_excavator_id");

                    b.ToTable("auction_offers", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.AutogeneratedMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ForWhom")
                        .HasColumnType("integer")
                        .HasColumnName("for_whom");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_autogenerated_messages");

                    b.ToTable("autogenerated_messages", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.Excavator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsForAuctionOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_for_auction_only");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_excavators");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_excavators_type_id");

                    b.ToTable("excavators", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.ExcavatorBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("brand");

                    b.HasKey("Id")
                        .HasName("pk_excavator_brands");

                    b.ToTable("excavator_brands", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.ExcavatorCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.HasKey("Id")
                        .HasName("pk_excavator_categories");

                    b.ToTable("excavator_categories", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.ExcavatorPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExcavatorId")
                        .HasColumnType("integer")
                        .HasColumnName("excavator_id");

                    b.Property<bool>("IsTitle")
                        .HasColumnType("boolean")
                        .HasColumnName("is_title");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("photo");

                    b.HasKey("Id")
                        .HasName("pk_excavator_photos");

                    b.HasIndex("ExcavatorId")
                        .HasDatabaseName("ix_excavator_photos_excavator_id");

                    b.ToTable("excavator_photos", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.ExcavatorProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExcavatorId")
                        .HasColumnType("integer")
                        .HasColumnName("excavator_id");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("property_type_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_excavator_properties");

                    b.HasIndex("ExcavatorId")
                        .HasDatabaseName("ix_excavator_properties_excavator_id");

                    b.HasIndex("PropertyTypeId")
                        .HasDatabaseName("ix_excavator_properties_property_type_id");

                    b.ToTable("excavator_properties", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.ExcavatorPropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InputType")
                        .HasColumnType("integer")
                        .HasColumnName("input_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_excavator_property_types");

                    b.ToTable("excavator_property_types", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.ExcavatorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.HasKey("Id")
                        .HasName("pk_excavator_types");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_excavator_types_brand_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_excavator_types_category_id");

                    b.ToTable("excavator_types", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.MainOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExcavatorTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("excavator_type_id");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("photo");

                    b.HasKey("Id")
                        .HasName("pk_main_offers");

                    b.HasIndex("ExcavatorTypeId")
                        .HasDatabaseName("ix_main_offers_excavator_type_id");

                    b.ToTable("main_offers", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.SparePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogNumber")
                        .HasColumnType("integer")
                        .HasColumnName("catalog_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_spare_parts");

                    b.ToTable("spare_parts", (string)null);
                });

            modelBuilder.Entity("ServISData.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_temporary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Residence")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("residence");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("surname");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ExcavatorPropertyTypeExcavatorType", b =>
                {
                    b.HasOne("ServISData.Models.ExcavatorType", null)
                        .WithMany()
                        .HasForeignKey("ExcavatorTypesWithThisPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_excavator_property_type_excavator_type_excavator_types_exca");

                    b.HasOne("ServISData.Models.ExcavatorPropertyType", null)
                        .WithMany()
                        .HasForeignKey("PropertyTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_excavator_property_type_excavator_type_excavator_property_t");
                });

            modelBuilder.Entity("ExcavatorSparePart", b =>
                {
                    b.HasOne("ServISData.Models.Excavator", null)
                        .WithMany()
                        .HasForeignKey("ExcavatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_excavator_spare_part_excavators_excavators_id");

                    b.HasOne("ServISData.Models.SparePart", null)
                        .WithMany()
                        .HasForeignKey("SparePartsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_excavator_spare_part_spare_parts_spare_parts_id");
                });

            modelBuilder.Entity("ServISData.Models.AdditionalEquipment", b =>
                {
                    b.HasOne("ServISData.Models.AdditionalEquipmentBrand", "Brand")
                        .WithMany("AdditionalEquipmentsOfThisBrand")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_additional_equipments_additional_equipment_brands_brand_id");

                    b.HasOne("ServISData.Models.AdditionalEquipmentCategory", "Category")
                        .WithMany("AdditionalEquipmentsOfThisCategory")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_additional_equipments_additional_equipment_categories_categ");

                    b.HasOne("ServISData.Models.ExcavatorCategory", "ExcavatorCategory")
                        .WithMany("AdditionalEquipmentsOfThisCategory")
                        .HasForeignKey("ExcavatorCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_additional_equipments_excavator_categories_excavator_catego");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("ExcavatorCategory");
                });

            modelBuilder.Entity("ServISData.Models.AdditionalEquipmentPhoto", b =>
                {
                    b.HasOne("ServISData.Models.AdditionalEquipment", "AdditionalEquipment")
                        .WithMany("Photos")
                        .HasForeignKey("AdditionalEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_additional_equipment_photos_additional_equipments_additiona");

                    b.Navigation("AdditionalEquipment");
                });

            modelBuilder.Entity("ServISData.Models.AuctionBid", b =>
                {
                    b.HasOne("ServISData.Models.AuctionOffer", "AuctionOffer")
                        .WithMany()
                        .HasForeignKey("AuctionOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auction_bids_auction_offers_auction_offer_id");

                    b.HasOne("ServISData.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auction_bids_users_user_id");

                    b.Navigation("AuctionOffer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServISData.Models.AuctionOffer", b =>
                {
                    b.HasOne("ServISData.Models.Excavator", "Excavator")
                        .WithMany()
                        .HasForeignKey("ExcavatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auction_offers_excavators_excavator_id");

                    b.Navigation("Excavator");
                });

            modelBuilder.Entity("ServISData.Models.Excavator", b =>
                {
                    b.HasOne("ServISData.Models.ExcavatorType", "Type")
                        .WithMany("ExcavatorsOfThisType")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_excavators_excavator_types_type_id");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ServISData.Models.ExcavatorPhoto", b =>
                {
                    b.HasOne("ServISData.Models.Excavator", "Excavator")
                        .WithMany("Photos")
                        .HasForeignKey("ExcavatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_excavator_photos_excavators_excavator_id");

                    b.Navigation("Excavator");
                });

            modelBuilder.Entity("ServISData.Models.ExcavatorProperty", b =>
                {
                    b.HasOne("ServISData.Models.Excavator", null)
                        .WithMany("Properties")
                        .HasForeignKey("ExcavatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_excavator_properties_excavators_excavator_id");

                    b.HasOne("ServISData.Models.ExcavatorPropertyType", "PropertyType")
                        .WithMany()
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_excavator_properties_excavator_property_types_property_type");

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("ServISData.Models.ExcavatorType", b =>
                {
                    b.HasOne("ServISData.Models.ExcavatorBrand", "Brand")
                        .WithMany("ExcavatorTypesOfThisBrand")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_excavator_types_excavator_brands_brand_id");

                    b.HasOne("ServISData.Models.ExcavatorCategory", "Category")
                        .WithMany("ExcavatorTypesOfThisCategory")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_excavator_types_excavator_categories_category_id");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ServISData.Models.MainOffer", b =>
                {
                    b.HasOne("ServISData.Models.ExcavatorType", "ExcavatorType")
                        .WithMany()
                        .HasForeignKey("ExcavatorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_main_offers_excavator_types_excavator_type_id");

                    b.Navigation("ExcavatorType");
                });

            modelBuilder.Entity("ServISData.Models.AdditionalEquipment", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("ServISData.Models.AdditionalEquipmentBrand", b =>
                {
                    b.Navigation("AdditionalEquipmentsOfThisBrand");
                });

            modelBuilder.Entity("ServISData.Models.AdditionalEquipmentCategory", b =>
                {
                    b.Navigation("AdditionalEquipmentsOfThisCategory");
                });

            modelBuilder.Entity("ServISData.Models.Excavator", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("ServISData.Models.ExcavatorBrand", b =>
                {
                    b.Navigation("ExcavatorTypesOfThisBrand");
                });

            modelBuilder.Entity("ServISData.Models.ExcavatorCategory", b =>
                {
                    b.Navigation("AdditionalEquipmentsOfThisCategory");

                    b.Navigation("ExcavatorTypesOfThisCategory");
                });

            modelBuilder.Entity("ServISData.Models.ExcavatorType", b =>
                {
                    b.Navigation("ExcavatorsOfThisType");
                });
#pragma warning restore 612, 618
        }
    }
}
