namespace ServISData.Attributes
{
    /// <summary>
    /// Represents an attribute used to define data for an autogenerated message.
    /// </summary>
    internal class AutogeneratedMessageDataAttribute : Attribute
	{
        /// <summary>
        /// Gets the label which defines the purpose of the autogenerated message. 
        /// </summary>
        /// <remarks>
        /// Can be used to display for the user. It should inform for whom the autogenerated message 
        /// is meant (possibly also in which scenario should be the autogenerated message used).
        /// </remarks>
        public string Label { get; }

        /// <summary>
        /// Gets the default subject of the autogenerated message.
        /// </summary>
        public string DefaultSubject { get; }

        /// <summary>
        /// Gets the default message body of the autogenerated message.
        /// </summary>
        public string DefaultMessage { get; }

        /// <summary>
        /// Gets the array of tags supported within the subject or message body of the autogenerated message.
        /// </summary>
        public string[] Tags { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="AutogeneratedMessageDataAttribute"/> class
        /// with the specified label, default subject, default message, and tags.
        /// </summary>
        /// <param name="label">The user-friendly label defining the autogenerated message.</param>
        /// <param name="defaultSubject">The default subject of the autogenerated message.</param>
        /// <param name="defaultMessage">The default message body of the autogenerated message.</param>
        /// <param name="tags">The array of tags supported within the subject or the message body of the autogenerated message.</param>
        public AutogeneratedMessageDataAttribute(string label, string defaultSubject, string defaultMessage, string[] tags)
		{
			Label = label;
			DefaultSubject = defaultSubject;
			DefaultMessage = defaultMessage;
			Tags = tags;
		}
	}
}
